.gitignore, CHANGELOG.md, README.md, lib/absinthe/relay/connection.ex, lib/absinthe/relay/node.ex, lib/absinthe/relay/schema.ex, mix.exs, mix.lock, test/lib/absinthe/relay/schema_test.exs, test/support/star_wars/schema.ex
This PR updates the schema notation used in the library to work with Absinthe v1.0, and introduces a nicer definition style for node-related schema mechanisms.
This _doesn't_ add Connection, which is the next sizable chunk of work.
Resolves #2
=> Update for Absinthe v1.0

lib/absinthe/relay/node/helpers.ex, lib/absinthe/relay/schema/notation.ex, test/lib/absinthe/relay/node_test.exs
This adds a function, `parsing_node_ids`, which can be used to wrap resolver functions to pre-parse node (global) ID arguments before they are passed on to the resolver.
This addresses the issue mentioned in #16.
Parse a node (global) ID argument `:item_id` (which should be an ID for the`:item` type)
```elixir
resolve parsing_node_ids(&my_field_resolver/2, item_id: :item)
```
=> Add a parsing_node_ids helper to ease resolver use

mix.exs, test/star_wars/object_identification_test.exs
It seems I spoke too soon when I said my problem was fixed – there are still cases where mutations return empty objects because of the way Relay inserts `... on Node` lines. Here is an extra test demonstrating the problem.
=> Add test with redundant (but valid) duplicate fragments

lib/absinthe/relay/mutation.ex
```
warning: variable "args" is unused
lib/absinthe/relay/mutation.ex:96
```
=> Fix warning

lib/absinthe/relay/connection.ex, test/lib/absinthe/relay/connection_test.exs, test/lib/absinthe/relay/pagination_test.exs, test/support/star_wars/schema.ex
Based on my conversation with @benwilson512 in the slack channel, this converts the from_* functions in Connection to return {:ok, connection} or {:error, reason} and returns {:error, reason} if the pagination args aren't set correctly.
This allows the developer to return graphql errors for missing params instead of a 500 error.
This changes the API for the from_* and limit functions
=> Makes the from_* methods in Absinthe.Relay.Connection return either {:ok, connection} or {:error, reason}

lib/absinthe/relay/connection.ex
This lets us drop an otherwise unnecessary intermediate Map creation.
=> Use Keyword.get/3 to read keyword list options

lib/absinthe/relay/node/parse_ids.ex, test/lib/absinthe/relay/node/parse_ids_test.exs
Previously, the ParseIDs middleware could only parse data structures
like:
```
middleware Absinthe.Relay.Node.ParseIDs, item_id: :item
middleware Absinthe.Relay.Node.ParseIDs, interface_id: [:item, :thing]
```
With this PR, you can parse nested data structures by passing nested
keyword lists.
```
middleware Absinthe.Relay.Node.ParseIDs, parent: [
id: :parent,
children: [id: :child],
child: [id: :child]
]
```
Solves https://github.com/absinthe-graphql/absinthe_relay/issues/56.
=> Allow ParseIDs to parse nested structures

README.md
Nothing major, but it does throw you off when reading the README at first. Considering the package is at > 1.0, it seems wise to remove this notice.
=> Remove note about being pre-1.0 in README

lib/absinthe/relay/connection.ex, test/lib/absinthe/relay/connection_test.exs
Hey guys, I was running some code and I discovered that the `Connection.offset(args)` will return `nil` if the `args` do not specify an offset. Since there is a `nil` return and we do `Connection.from_slice(posts, offset)` we will get, as I generated from the test:
```elixir
1) test .from_slice/2 when the offset is nil it will set default offset to 1 (Absinthe.Relay.ConnectionTest)
test/lib/absinthe/relay/connection_test.exs:195
** (ArithmeticError) bad argument in arithmetic expression
code: Connection.from_slice([%{foo: :bar}], nil)
stacktrace:
(absinthe_relay) lib/absinthe/relay/connection.ex:425: Absinthe.Relay.Connection.build_cursors/2
(absinthe_relay) lib/absinthe/relay/connection.ex:287: Absinthe.Relay.Connection.from_slice/3
test/lib/absinthe/relay/connection_test.exs:196: (test) …
```
=> fix arithmetic error when offset is nil

lib/absinthe/relay/mutation.ex, lib/absinthe/relay/node/parse_ids.ex, test/lib/absinthe/relay/node/parse_ids_test.exs
=> Node.ParseIDs: Fix schema/argument mismatch due to mutation middleware arg stripping

lib/absinthe/relay/connection.ex
The `offset_and_limit_for_query` change is because I couldn't figure out what that error meant until I read the source code a couple of times. I know that's only evidence from one person, but I hope it can help someone else in the future.
=> Documentation changes on Connection limit and offset_and_limit_for_query

lib/absinthe/relay/schema/notation.ex, mix.exs, mix.lock, test/lib/absinthe/relay/connection_test.exs, test/lib/absinthe/relay/mutation/classic_test.exs, test/lib/absinthe/relay/mutation/modern_test.exs, test/lib/absinthe/relay/node/parse_ids_test.exs, test/lib/absinthe/relay/node_test.exs, test/lib/absinthe/relay/pagination_test.exs, test/lib/absinthe/relay/schema_test.exs, test/star_wars/connection_test.exs, test/star_wars/object_identification_test.exs, test/support/case.ex, test/support/star_wars/schema.ex
- Update deps for absinthe, earmark, ex_doc
- Remove ex_spec
- Convert ExSpec `it` -> `test`
- Restructure tests for modern/classic split
- Clean up warning text
=> Modernize Tests

lib/absinthe/relay/node.ex, test/lib/absinthe/relay/node_test.exs
Fixes #83
Previously, if middleware had put an error result into the resolution,
querying a node would result in an error because of a missing pattern
match for Absinthe.Relay.Node.resolve_with_global_id/2. This pull
request introduces a test with a minimal schema/query necessary to
trigger the error, and a simple addition of the missing function head
necessary to restore expected behavior.
=> Handle middleware error resolutions when resolving node queries.

LICENSE.md, README.md, mix.exs
In the unlikely event that any contributors object to this change,
please contact the maintainers.
This also changes the copyright notice from our company, CargoSense,
to the maintainers, as the scope/focus of the project has changed in
the last year.
=> Switch license to MIT

CHANGELOG.md, lib/absinthe/relay/node.ex, lib/absinthe/relay/node/parse_ids.ex, lib/absinthe/relay/node/parse_ids/rule.ex, test/lib/absinthe/relay/node/parse_ids_test.exs
This PR adds support for parsing `null` values as input for the `Absinthe.Relay.Node.ParseIDs` middleware input.
When a `null` is encountered, it is passed through as a `nil` argument value. Note this is also true when multiple possible types are valid for the argument—since no type can be identified, no wrapping `%{type: _, id: nil}` is necessary. Just match for bare `nil` values in your resolvers.
Resolves #82.
=> Support null value parsing in ParseIDs middleware

lib/absinthe/relay/connection.ex, test/lib/absinthe/relay/connection_test.exs, test/lib/absinthe/relay/node_test.exs
Support empty cursors even if first or last is present.
=> Support empty cursors with first or last variable present

lib/absinthe/relay/mutation.ex, test/lib/absinthe/relay/node/parse_ids_test.exs
=>  Fix parsing of node IDs with local middleware in modern schemas (v1.4)

lib/absinthe/relay/connection.ex, lib/absinthe/relay/connection/notation.ex, test/lib/absinthe/relay/connection_test.exs
This PR allows you to override the `:node` resolver for an Relay connection.
This is useful in a number of scenarios, but particularly when working with a data source (such as NoSQL) that represents relationships as arrays of foreign keys that you still want to page over.
My previous solution was to simply use `Connection.from_list` and modify the node edge in the resolver, but that's hacky and doesn't support the niceties of the batch middleware out of the box.
This PR enables overriding `:node` and inserts a default implementation if none is provided. Unfortunately, the only way I managed to figure out how was by parsing the provided block and looking for the specified field, but it seems to work well enough.
Tried to update the docs as best as I could as well!
=> Customize the node resolver

mix.exs
When running ex_doc, if this value is set then each function will link
to the relevant line on GitHub.
=> Include source_url in mix.exs so that code is linked from the docs

lib/absinthe/relay/connection.ex, test/lib/absinthe/relay/connection_test.exs
Previously a query with an invalid cursor (one which either wasn't valid base64, didn't have the correct prefix, or didn't contain a valid integer) would cause a crash. This change makes it return an error consistent with other behaviour on bad client input.
=> Invalid cursor error handling

lib/absinthe/relay/connection.ex, test/lib/absinthe/relay/pagination_test.exs, test/star_wars/connection_test.exs
Fixes #111 
This updates the logic behind `hasPreviousPage` and `hasNextPage` to follow the latest version of the Relay Cursor Connections spec:
https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields
When paginating forwards with `first` it's now permitted to return true when a previous page exists. Likewise, when paginating backwards with `last`, it's now permitted to return true when a next page exists. This is pretty handy for bidirectional pagination.
The tests for the `pageInfo` object were already in place, so I just updated the expectations.  Let me know if there are additional tests I should add.
Although it follows the spec, it seems like it could be a breaking change for users expecting the old behavior.
=> Updates logic for hasPreviousPage/hasNextPage based on latest Relay spec

lib/absinthe/relay/connection.ex
V1.4.3 introduced a breaking change in this function that used return an `integer`, that is not reflected in the documentation.
=> Fix typespec of Connection.cursor_to_offset/1

lib/absinthe/relay/connection.ex, test/lib/absinthe/relay/connection_test.exs
In the [spec](https://facebook.github.io/relay/graphql/connections.htm#sec-Edge-Types.Fields) for connections described by Facebook, edges can be defined with arbitrary fields.
This pull request provides additional capabilities to the `Absinthe.Relay.Connection` module, specifically via changes to the private `build_cursors` functions to allow resolving of edge data.
For example:
```graphql
{
team(id: 1) {
users(first: 5) {
edges {
role
node {
email
}
}
}
}
}
```
While Absinthe Relay does support defining fields on edges, these fields can only be resolved based on data already provided on the node. In many cases it may be useful to have edge data resolved from a database query or other service.
=> Enhancements to Connection builder functions to allow inclusion of edge data

lib/absinthe/relay/node/parse_ids.ex, test/lib/absinthe/relay/node/parse_ids_test.exs
This pull request fixes a crash scenario when the `ParseIDs` middleware is used to decode opaque ids stored in a sub-field of a nullable argument.
With this change it will become possible to make a mutation call such as `mutation foo($input: null) { ... }` and allow for `ParseIDs` to be configured to decode `input: [some_id: :some_type]`
=> Introduce a test and fix for ParseIDs to handle nullable input objects.

lib/absinthe/relay/connection/notation.ex, test/lib/absinthe/relay/connection_test.exs
Fixes #130. Ideally this bugfix would be backported to v1.4 too so it'd be in a non-beta release.
=> add connection/2 macro

lib/absinthe/relay/connection.ex
Just mention a small error or typo in the Relay.Connection.from_slice/3 docs
=> Fix Relay.Connection.from_slice/3 documentation

lib/absinthe/relay/connection.ex
The current spec defined all the keys, but didn't mark them as optional. That means that if you skip a key (as opposed to explicitly setting it to nil), typechecking will fail.
=> Fix typespec for from_query/5 options.

lib/absinthe/relay/connection.ex
The `max` keyword was missing.
It will fix dialer errors as described in absinthe-graphql/absinthe_relay#133.
=> Update `Absinthe.Relay.Connection.from_query` spec

lib/absinthe/relay/connection.ex, test/lib/absinthe/relay/connection_test.exs
Passing a `nil` value on a nullable input argument should be functionally equivalent to not passing that argument at all. This enables the client to always populate the `:first`/`:last`/`:before`/`:after` arguments, but use `null` values on the ones that should be ignored.
I included a test here which fails until this code change is made. We noticed this in our app because backward pagination wasn't working correctly on the following connection input arguments:
```json
{
"after": null,
"before": "YXJyYXljb25uZWN0aW9uOjI=",
"first": null,
"last": 2,
}
```
As I understand it, this _should_ produce the exact same output on a Relay connection with the following input arguments:
```json
{
"before": "YXJyYXljb25uZWN0aW9uOjI=",
"last": 2,
}
```
But without this PR's change, `absinthe_relay` does …
=> Bug fix: ignore nil first and last in pagination

lib/absinthe/relay/connection.ex
Fix for issue #159 
Changes `before` and `after` parameters to `Connection.cursor()`, and `first` and `last` to positive integers.
=> Fix: default connection options type

lib/absinthe/relay/connection.ex, test/lib/absinthe/relay/connection_test.exs
from_list has handled, but from_query not
https://github.com/absinthe-graphql/absinthe_relay/blob/c3c85ca88adb8e925e846a515f75d93224b1f17d/lib/absinthe/relay/connection.ex#L338-L342
=> fix: if offset is less than limit, set limit to offset

lib/absinthe/relay/mutation/notation/classic.ex, lib/absinthe/relay/node/parse_ids.ex, test/lib/absinthe/relay/node/parse_ids_test.exs
Absinthe.Relay.Node.ParseIDs causes runtime error if occurs more than once in a mutation query.
This happens because in `mutation.ex`, `__parse_ids_root` is set at a global level on the resolution.
Once the `ParseIDs.ex` middleware is hit, it works great from a parent mutation but if `ParseIDs` is called in any of the child fields it blows up because it is expecting `input` to be set when it isn't for the child field.
This does two things:
1. pattern matches on `find_schema_root!` so that it will identify if it is the parent mutation by matching on the 
```
%{
__private__: [
absinthe_relay: [
payload: {:fill, _},
input: {:fill, _}
]
]
}
```
structure.
The other pattern-match function is for the child fields.
2. There was a discrepancy between the `modern.ex` and `classic.ex` modules in …
=> Absinthe.Relay.Node.ParseIDs causes runtime error if occurs more than once in a mutation query

lib/absinthe/relay/node.ex, lib/absinthe/relay/node/notation.ex, test/lib/absinthe/relay/schema_test.exs
In one of my projects I'm using custom `UUID` type for all `:id` fields.
But node interface and objects have `:id` field with fixed `ID` type. Because of that resulting schema does not look consistent.
In this PR I've added `:id_type` attribute which allow one to pass his own types for `:id` fields.
=> Allow custom :id field type for node

lib/absinthe/relay/connection.ex, test/lib/absinthe/relay/connection_test.exs, test/lib/absinthe/relay/schema_test.exs
This fixes #152 and #161 so that we are able to set custom cursors on edges.
As explained in #152, the reasons for why we may want to set and handle our own cursors are as follows:
1. We could be interfacing with external services that use their own cursors, or don't paginate using offset/limit.
2. Currently the cursors in this package just encode the OFFSET and OFFSET + LIMIT. But we may not want to use OFFSET in our SQL queries because it results in [slow performance for large offsets.](https://use-the-index-luke.com/sql/partial-results/fetch-next-page)
=> fix: enable overriding the default cursor for an edge [#152] [#161]

lib/absinthe/relay/node/notation.ex, mix.exs
Fixes some compiles warnings:
1. https://github.com/absinthe-graphql/absinthe_relay/issues/171
2.
```
Generated ecto app
==> absinthe_relay
Compiling 22 files (.ex)
warning: clauses with the same name and arity (number of arguments) should be grouped together, "defmacro node/2" was previously defined (lib/absinthe/relay/node/notation.ex:23)
lib/absinthe/relay/node/notation.ex:40
warning: clauses with the same name and arity (number of arguments) should be grouped together, "defmacro node/2" was previously defined (lib/absinthe/relay/node/notation.ex:23)
lib/absinthe/relay/node/notation.ex:55
```
=> Fix Elixir 1.11 compiles warning

.github/workflows/test.yml, .travis.yml
Hello.
I've realized that there are no tests running at commit/PR into your repo.
It seems that you've previously used TravisCI for that. I'm not sure why is it disabled now, but I faced the issue with their new billing plans and too strict limitations for running builds for open source projects.
What do you think about migrating to Github Actions? It's actually quite easy to do.
=> Use Github Actions instead of TravisCI

.github/workflows/test.yml, mix.exs
According to https://github.com/absinthe-graphql/dataloader/pull/121/files/c91311bb0e05fbc3911067d5e1756ce780b28b60#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88:
```
Absinthe tends to only support the last 2 Elixir versions, so we can remove 1.7-1.9. This does need to be updated in our mix.exs probably.
```
Let's update it.
=> Support only 2 latest versions of Elixir

lib/absinthe/relay/connection.ex
This PR fixes a couple dialyzer warnings around missing types. Additionally, it allows other keys in maps passed to functions that expect `Absinthe.Relay.Connection.Options.t()` (useful for when these arguments come from Absinthe resolver args, where other unrelated args may also be present).
```elixir
defmodule MyApp.Schema do
query do
connection(field(:users)) do
arg :is_banned, non_null(:boolean)
resolve fn _, %{is_banned: is_banned} = args, _ ->
users = UsersService.list()
Connection.from_list(users, args) # this line raises a dialyzer warning,
end
end
end
end
```
=> fix Dialyzer warnings

lib/absinthe/relay/node/parse_ids.ex, test/lib/absinthe/relay/node/parse_ids_test.exs
When you have a field that has metadata attached to it such as:
```
payload field(:update_parent_local_middleware_with_meta, meta: [key: :val]) do
...
```
it puts that metadata into `%{__private__: [meta: [key: :val]]}`. But that makes it so that the existing pattern match in `find_schema_root!` no longer works because keyword list pattern matching is awkward and it eventually raises the error `"Could not find schema_node for #{key}"`.
This PR makes it so that it doesn't try to pattern match on the keyword list, but moves the match into the function body itself, returning the original fallback if the match does not work.
=> Parse ids and meta info

lib/absinthe/relay/connection/notation.ex, test/lib/absinthe/relay/connection_test.exs
When a connection is set up with `paginate: :forward` or `paginate: :backward`, the corresponding slice argument (`first` or `last`) is actually required.
This change creates the right type `Int!` for the argument in those cases.
=> With restricted pagination, force first or last to be given

README.md, lib/absinthe/relay/connection.ex, lib/absinthe/relay/node.ex, mix.exs
Changed deprecated `Logger.warn` to `Logger.warning`
Updated README to min Elixir 1.11
On CI we already started from 1.11
```
include:
- pair:
elixir: "1.11.x"
otp: "22.x"
- pair:
elixir: "1.15.x"
otp: "26.x"
```
Updated version to `1.6`, maybe use 1.5.3 is better?
=> Fix Logger warnings

.github/workflows/test.yml, test/support/star_wars/database.ex
List of changes:
- add Elixir 1.18 to matrix pair in CI
- bump GitHub Actions
- resolve typing warning
=> Support Elixir 1.18 in CI
